export const HISTORY_MODAL_MIN_HEIGHT = 0;
export const HISTORY_MODAL_DEFAULT_HEIGHT = 250;
export const HISTORY_MODAL_MAX_HEIGHT = 700;

export const TESTCASE_MAKER_TEXTAREA_DFEAULT_HEIGHT = 100;
export const TESTCASE_MAKER_TEXTAREA_MIN_HEIGHT = 0;

export const HISTORY_MAX_LENGTH = 100;
